version: '3'

services:
  web:
    image: nginx
    container_name: 'web'
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - 7000:80

  reverse-proxy:
    build: ./reverse-proxy
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
